"""
Configuration parameters for the network simulation. We have modified parameters to simulate real world, of course, not perfectly
"""

# Time 
SENSING_INTERVAL = 15  
TDMA_SLOT_DURATION = 10  
TDMA_CYCLE_DURATION = 3600  

# Communication 
BAUD_RATE = 300  
FREQUENCY_BAND = (401, 402)  

# Data 
RAW_PACKET_SIZE = 375  
USABLE_PAYLOAD = 250  
PROTOCOL_OVERHEAD = RAW_PACKET_SIZE - USABLE_PAYLOAD  

# Network 
NUM_NODES = 5  
SATELLITE_PROPAGATION_DELAY = 0.25  

# Data collection 
DATA_POINTS_PER_PACKET = 10  
SENSOR_ACCURACY = 0.95  

# Power consumption 
TX_VOLTAGE = 12.0  
TX_CURRENT = 1.8  
STANDBY_VOLTAGE = 12.0  
STANDBY_CURRENT = 0.0028  
GPS_VOLTAGE = 12.0  
GPS_CURRENT = 0.025  
GPS_FIX_DURATION = 60  

# Energy 
TX_ENERGY_PER_TRANSMISSION = TX_VOLTAGE * TX_CURRENT * TDMA_SLOT_DURATION  
TX_ENERGY_PER_TRANSMISSION_WH = TX_ENERGY_PER_TRANSMISSION / 3600  
TX_ENERGY_PER_DAY = TX_ENERGY_PER_TRANSMISSION_WH * 24  
STANDBY_ENERGY_PER_DAY = STANDBY_VOLTAGE * STANDBY_CURRENT * 24  
GPS_ENERGY_PER_DAY = GPS_VOLTAGE * GPS_CURRENT * GPS_FIX_DURATION * 24 / 3600  
TOTAL_ENERGY_PER_DAY = TX_ENERGY_PER_DAY + STANDBY_ENERGY_PER_DAY + GPS_ENERGY_PER_DAY  
TOTAL_NETWORK_ENERGY_PER_DAY = TOTAL_ENERGY_PER_DAY * NUM_NODES  

# Data throughput 
DATA_PER_TRANSMISSION = USABLE_PAYLOAD  
DATA_PER_DAY = DATA_PER_TRANSMISSION * 24  
TOTAL_NETWORK_DATA_PER_DAY = DATA_PER_DAY * NUM_NODES  
RAW_NETWORK_DATA_PER_DAY = RAW_PACKET_SIZE * 24 * NUM_NODES  

# Time efficiency 
ACTIVE_TIME_PER_DAY = TDMA_SLOT_DURATION * 24  
TOTAL_TIME_PER_DAY = 24 * 3600  
CHANNEL_UTILIZATION = ACTIVE_TIME_PER_DAY / TOTAL_TIME_PER_DAY * 100  

# Visualization 
PLOT_REFRESH_RATE = 1  
ANIMATION_SPEED = 1  